-- Followship Database Base Schema
-- Creates the followship database with standard TrinityCore update tracking tables
-- and the bot_owners table (moved from characters database, renamed from followship_bot_owners)

CREATE TABLE `updates` (
  `name` varchar(200) NOT NULL COMMENT 'filename with extension of the update.',
  `hash` char(40) DEFAULT '' COMMENT 'sha1 hash of the sql file.',
  `state` enum('RELEASED','CUSTOM','MODULE') NOT NULL DEFAULT 'RELEASED' COMMENT 'defines if an update is released or archived.',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'timestamp when the query was applied.',
  `speed` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'time the query takes to apply in ms.',
  PRIMARY KEY (`name`) USING BTREE,
  UNIQUE KEY `unique_index` (`name`,`hash`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='List of all applied updates in this database.';

CREATE TABLE `updates_include` (
  `path` varchar(200) NOT NULL COMMENT 'directory to include. $ means relative to the source directory.',
  `state` enum('RELEASED','CUSTOM','MODULE') NOT NULL DEFAULT 'RELEASED' COMMENT 'defines if the directory contains released or archived updates.',
  PRIMARY KEY (`path`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='List of directories containing update files.';

INSERT INTO `updates_include` (`path`, `state`) VALUES
('$/sql/updates/followship', 'RELEASED');

CREATE TABLE `bot_owners` (
  `bot_id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `bot_guid` BIGINT UNSIGNED NOT NULL,
  `bot_entry` INT UNSIGNED NOT NULL,
  `player_guid` BIGINT UNSIGNED NOT NULL,
  `hire_expiry_time` BIGINT UNSIGNED NOT NULL,

  UNIQUE KEY `uq_bot_player` (`bot_guid`, `player_guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `bot_templates` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `bot_class` TINYINT UNSIGNED NOT NULL,
  `bot_race` TINYINT UNSIGNED NOT NULL,
  `companion_spell` INT UNSIGNED NOT NULL DEFAULT 0,
  `chatter_type` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `gender` TINYINT UNSIGNED NOT NULL DEFAULT 2,
  `pet_source` INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Bot template definitions (moved from hardcoded BotEntryClassTable)';

CREATE TABLE `bot_chatter_lines` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `zoneId` INT NOT NULL DEFAULT 0,
  `fsbRaceId` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `fsbClassId` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `category` SMALLINT UNSIGNED NOT NULL,
  `chatter_type` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `line_text` TEXT NOT NULL,
  `comment` VARCHAR(255) DEFAULT NULL,
  UNIQUE KEY `uq_line` (`category`, `chatter_type`, `line_text`(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Bot chatter reply lines';

INSERT INTO `bot_templates` (`entry`, `bot_class`, `bot_race`, `companion_spell`, `chatter_type`, `gender`, `pet_source`) VALUES
-- Priests
(141508, 2, 1, 0, 1, 2, 0),
(375, 2, 1, 10675, 2, 1, 0),
(376, 2, 1, 0, 2, 1, 0),
(377, 2, 1, 70613, 2, 1, 0),
(837, 2, 2, 0, 3, 0, 0),
(3595, 2, 3, 0, 2, 1, 0),
(5484, 2, 1, 0, 1, 0, 0),
(5489, 2, 1, 0, 2, 0, 0),
(16502, 2, 5, 0, 1, 0, 0),
(49749, 2, 1, 0, 2, 1, 0),
-- Warriors
(911, 1, 1, 0, 2, 0, 0),
(912, 1, 2, 0, 1, 0, 0),
(913, 1, 1, 171118, 2, 1, 0),
(914, 1, 1, 0, 2, 0, 0),
(3593, 1, 3, 15067, 2, 1, 0),
(16503, 1, 5, 0, 1, 0, 0),
(46405, 1, 1, 0, 3, 0, 0),
(49736, 1, 1, 0, 3, 0, 0),
(50595, 1, 1, 0, 3, 2, 0),
(112912, 1, 1, 0, 1, 0, 0),
(164939, 1, 2, 0, 3, 1, 0),
(164940, 1, 7, 0, 1, 0, 0),
-- Mages
(198, 3, 1, 10697, 1, 0, 0),
(328, 3, 1, 10696, 1, 0, 0),
(16500, 3, 5, 0, 3, 1, 0),
(37121, 3, 2, 0, 1, 1, 0),
(43006, 3, 3, 0, 2, 1, 0),
(49760, 3, 1, 1263739, 2, 1, 0),
-- Paladins
(925, 6, 1, 0, 3, 0, 0),
(926, 6, 2, 0, 1, 0, 0),
(927, 6, 1, 0, 1, 0, 0),
(928, 6, 1, 0, 2, 0, 0),
(5491, 6, 1, 0, 3, 0, 0),
(5492, 6, 1, 0, 2, 1, 0),
(16501, 6, 5, 408311, 2, 0, 0),
(49741, 6, 1, 1269627, 2, 1, 0),
-- Warlocks
(459, 8, 1, 153252, 2, 1, 0),
(461, 8, 1, 0, 3, 1, 0),
(906, 8, 1, 0, 2, 0, 0),
(5495, 8, 1, 0, 3, 1, 0),
(6373, 8, 1, 0, 2, 0, 0),
(6374, 8, 1, 0, 1, 1, 0),
(49769, 8, 1, 0, 1, 1, 0),
-- Druids
(3597, 5, 3, 15067, 1, 0, 0),
(5506, 5, 3, 0, 1, 0, 0),
-- Rogues
(915, 4, 1, 0, 1, 0, 0),
(917, 4, 1, 0, 3, 1, 0),
(918, 4, 1, 0, 1, 0, 0),
(5505, 4, 3, 0, 3, 0, 0),
(13283, 4, 1, 0, 1, 0, 0),
(49745, 4, 1, 0, 2, 0, 0),
(173819, 4, 1, 0, 3, 1, 0),
-- Hunters
(895, 7, 2, 0, 3, 0, 1125),
(5516, 7, 2, 0, 1, 0, 191979),
(43011, 7, 1, 0, 3, 1, 44628),
(43278, 7, 1, 0, 3, 1, 43292),
(46983, 7, 1, 0, 2, 0, 46982),
-- Monks
(63258, 10, 7, 17707, 2, 0, 0),
(63331, 10, 7, 0, 1, 0, 0),
(63285, 10, 7, 345740, 2, 0, 0),
(63235, 10, 7, 0, 1, 0, 0),
-- Shamans
(17089, 9, 5, 0, 3, 0, 0),
(20407, 9, 5, 0, 2, 1, 0);

-- Bot chatter lines: emote_kiss (category = 30)
INSERT INTO `bot_chatter_lines` (`zoneId`, `fsbRaceId`, `fsbClassId`, `category`, `chatter_type`, `line_text`, `comment`) VALUES
-- FSB_ChatterType::Neutral (1)
(0, 0, 0, 30, 1, 'Oh. thank you, I guess?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'What was that for?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'You\'re full of surprises today.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Well. that was unexpected.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'A kiss? Really now?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Uh. okay then.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Was that meant for me?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Not sure what that was about.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Huh. interesting choice.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Well, that happened.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Is this a new thing you\'re doing?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'ll pretend that made sense.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Unexpected, but alright.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'You do you, I guess.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Not sure how to respond to that.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Was that intentional?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'m. just going to ignore that.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'If that was a signal, I missed it.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I suppose that\'s one way to greet someone.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'You\'re full of surprises, aren\'t you?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'ll take that as. something.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Is this normal for you?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'m not sure what you expect from me now.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Well, that\'s one way to pass the time.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'ll just act like that was totally normal.', 'emote_kiss, Neutral'),
-- FSB_ChatterType::Positive (2)
(0, 0, 0, 30, 2, 'Oh. thank you, That is so sweet...', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'For me? Ah thank you!', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re full of surprises today.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Well. that makes my day.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'A kiss? Ah sure, why not...', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Aww, that\'s adorable!', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Well aren\'t you sweet!', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Oh! That made me smile.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re too kind, really.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That brightened my day, thank you.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You always know how to make things nicer.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Oh! I wasn\'t expecting that, but I liked it.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re such a charmer, {bot}.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That was lovely. thank you.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re making me blush over here.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'How cute! Do it again.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re surprisingly affectionate today.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That was sweet - keep it up.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You know how to make someone feel appreciated.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That was actually really nice.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re full of warmth today.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'A kiss? I won\'t say no to that.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re making this adventure much more pleasant.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That was unexpectedly lovely.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re such a softie sometimes.', 'emote_kiss, Positive'),
-- FSB_ChatterType::Negative (3)
(0, 0, 0, 30, 3, 'Oh. no thanks...', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Can you please, just... not do that?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'You\'re at it again?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Not this shit again...', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Just stop it!', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Ugh. really?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Do you mind? Actually, yes, you do.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Why are you like this?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Stop that. Seriously.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'If you do that again, I\'m walking.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'I did NOT ask for that.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Gross. Just. gross.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Are you trying to annoy me?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'That was unnecessary.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Please keep your lips to yourself.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Nope. Absolutely not.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'You think that was cute? It wasn\'t.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'I swear, you\'re doing this on purpose.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Can you not?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'That better not become a habit.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'I\'m not in the mood for your nonsense.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Try that again and see what happens.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'You\'re testing my patience.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'That was the opposite of charming.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'I regret standing this close to you.', 'emote_kiss, Negative'),
-- FSB_ChatterType::Cynical (4)
(0, 0, 0, 30, 4, 'A kiss? How quaint. And utterly meaningless.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'I suppose you think that fixes everything.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Save it for someone who still believes in fairy tales.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'How... romantic. Truly, my heart is aflutter.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Let me guess, you\'ve got an agenda behind this too.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Oh good, performative affection. My favorite.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Do you practice that in a mirror, or does it come naturally?', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'I\'m sure this gesture is completely selfless.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Charming. And completely hollow.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'I\'ve seen more sincerity in a used-car salesman.', 'emote_kiss, Cynical'),
-- FSB_ChatterType::Bitter (5)
(0, 0, 0, 30, 5, 'Don\'t patronize me with affection.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'I don\'t want your pity kiss.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'Keep your lips to yourself.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'After everything, you think a kiss fixes this?', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'Some wounds don\'t heal with kisses, they fester.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'You\'re too late for that. Way too late.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'Save your affection for someone who still believes in it.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'I\'ve tasted enough false hope to know better.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'A kiss? That\'s what I get? Figures.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'You kiss like an apology that isn\'t actually sorry.', 'emote_kiss, Bitter'),
-- FSB_ChatterType::Cold (6)
(0, 0, 0, 30, 6, '...', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'Unnecessary.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'That was inefficient.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'Acknowledged.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'No strategic value gained.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'This does not alter our trajectory.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'Processing complete.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'Physical contact logged. No further action required.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'The gesture has been noted and filed.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'I fail to see the operational benefit.', 'emote_kiss, Cold'),
-- FSB_ChatterType::Guarded (7)
(0, 0, 0, 30, 7, 'What are you trying to prove?', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'I don\'t trust gestures like that.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'What\'s the angle here?', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'Who put you up to this?', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'I\'ve been burned by kindness before.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'Is this a setup? It feels like a setup.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'I\'ll remember this. Whether that\'s good or bad depends on you.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'You\'re going to have to earn my trust with more than that.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'I don\'t let my guard down for just anyone. Try harder.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'What do you want? Nobody gives something for nothing.', 'emote_kiss, Guarded'),
-- FSB_ChatterType::Serious (8)
(0, 0, 0, 30, 8, 'We have objectives to complete.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Focus on the mission.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Sentimentality is a liability.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'There will be time for this later. After the battle.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Emotional distractions cost lives. Keep your head clear.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'The enemy does not pause for affection. Neither should we.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'If you have energy for this, you have energy to scout ahead.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Discipline now. Celebration after victory.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Every second wasted is a second the enemy gains.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'I need you sharp, not sentimental.', 'emote_kiss, Serious'),
-- FSB_ChatterType::Dry (9)
(0, 0, 0, 30, 9, 'Well, that happened.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'Noted.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'I\'ll add that to my list of unexpected events.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'Interesting choice. Bold, even.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'Your spontaneity is... documented.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'I\'ll pretend I didn\'t notice the enthusiasm.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'There goes my theory that you were predictable.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'That was certainly a thing that occurred.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'I suppose someone had to break the tension.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'My emotional response is pending. Do not wait for it.', 'emote_kiss, Dry'),
-- FSB_ChatterType::Curious (10)
(0, 0, 0, 30, 10, 'What prompted that? Was it instinct or intent?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Fascinating. What\'s the social protocol for returning that?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Do you kiss everyone, or am I special?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Is this a cultural ritual I\'m unaware of?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'I\'m noting the micro-expressions that preceded it.', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Statistically, was I the optimal target for that?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Your approach vector was surprisingly direct.', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'What variables led to this specific decision?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'I wonder if the outcome matches your hypothesis.', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'That raises far more questions than it answers.', 'emote_kiss, Curious'),
-- FSB_ChatterType::Warm (11)
(0, 0, 0, 30, 11, 'That was lovely, thank you.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'You always know how to brighten my day.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'A little kindness goes a long way.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'You have no idea how much I needed that.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'It\'s the small things with you. And this was perfect.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'You make the world feel a little softer.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'That went straight to my heart. Thank you.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'I don\'t say it enough, but you mean a lot to me.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'Moments like this remind me why I\'m glad you\'re here.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'You\'re like sunlight on a cold morning.', 'emote_kiss, Warm'),
-- FSB_ChatterType::Enthusiastic (12)
(0, 0, 0, 30, 12, 'Oh! Oh wow! That was AMAZING!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'YES! Best. Kiss. EVER!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'I am officially the happiest bot in Azeroth!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'CAN WE DO THAT AGAIN? PLEASE?', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'I need to sit down. My knees are literally weak!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'SOMEONE PINCH ME, I MUST BE DREAMING!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'That was like... fireworks! Actual fireworks!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'I\'m going to tell EVERYONE about this!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'My heart is doing BACKFLIPS right now!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'Is this real life? Because that felt LEGENDARY!', 'emote_kiss, Enthusiastic'),
-- FSB_ChatterType::Cheerful (13)
(0, 0, 0, 30, 13, 'Aww, that\'s sweet! Made my whole day!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'You\'re just the best, you know that?', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'Mwah! Right back at ya!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'Haha, you\'re such a softie! I love it!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'You just turned a normal day into a great one!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'I should bottle that feeling and sell it!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'Hey, who\'s the lucky one here? Oh, it\'s me!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'You\'re like a walking sunshine factory!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'If smiles were currency, I\'d be rich right now!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'That deserves a happy dance! *does a little spin*', 'emote_kiss, Cheerful'),
-- FSB_ChatterType::Devoted (14)
(0, 0, 0, 30, 14, 'Your affection means everything to me.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'I live for moments like this with you.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'My heart is yours, always.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'I would follow you through any darkness for moments like this.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'Every kiss is a promise I intend to keep.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'You are my anchor, my home, my everything.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'I don\'t need the world when I have you.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'With you, I am whole. Without you, I am incomplete.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'My soul recognized yours long before my lips did.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'Eternity would not be enough time to show you my love.', 'emote_kiss, Devoted'),
-- FSB_ChatterType::Morbid (15)
(0, 0, 0, 30, 15, 'Your lips are warm... for now.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'Kiss me while you still have lips.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'One day I\'ll kiss your corpse goodbye.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'Death makes every kiss sweeter. Especially yours.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'I wonder if rigor mortis preserves kisses.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'The grave is cold. Your lips are a nice preview.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'I\'ll remember the taste of your life. Until it fades.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'Every kiss brings you closer to your last breath.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'Beautiful. And fleeting. Like all good things before decay.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'I collect last kisses. Yours will be my favorite.', 'emote_kiss, Morbid'),
-- FSB_ChatterType::Narcissist (16)
(0, 0, 0, 30, 16, 'Of course you\'d want to kiss perfection.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'Mmm, you taste like admiration.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'I\'m sure that made your entire life.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'You\'re welcome. Not many get that privilege.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'I don\'t blame you. I\'d want to kiss me too.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'That must have been the highlight of your existence.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'Memorize that feeling. You\'ll never get better.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'I hope you realize how lucky you just got.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'My lips are basically a tourist attraction at this point.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'You may now tell people you kissed greatness.', 'emote_kiss, Narcissist'),
-- FSB_ChatterType::Sadist (17)
(0, 0, 0, 30, 17, 'I wonder if you\'d kiss me if I bit you.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Your lips tremble. I like that.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Too bad I don\'t feel anything.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Was that fear I felt, or just excitement?', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'I could hurt you. But this is more fun for now.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Your hesitation is delicious. Do it again.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'I love how you flinch but don\'t pull away.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'You\'re trembling. Good. Stay afraid.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'I\'ll let you live... because that kiss amused me.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Beg me for another. I want to hear it.', 'emote_kiss, Sadist'),
-- FSB_ChatterType::Hyperthymic (18)
(0, 0, 0, 30, 18, 'WOOOO! KISS CAM! WE\'RE ON THE KISS CAM!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'EVERYONE LOOK! WE JUST KISSED! THIS IS THE BEST!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'I\'M NEVER WASHING THESE LIPS AGAIN!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'DID YOU FEEL THAT? THE UNIVERSE JUST SHIFTED!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'I AM LITERALLY ASCENDING RIGHT NOW!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'SOMEBODY GET ME A TROPHY FOR BEST MOMENT EVER!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'MY HEART IS GOING TO EXPLODE AND I\'M OKAY WITH IT!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'THIS IS OFFICIALLY THE GREATEST DAY IN THE HISTORY OF DAYS!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'I WANT TO SHOUT IT FROM THE TOP OF ORGRIMMAR!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'I AM RUNNING IN CIRCLES BECAUSE I CANNOT CONTAIN THIS JOY!', 'emote_kiss, Hyperthymic'),
-- FSB_ChatterType::Autotelic (19)
(0, 0, 0, 30, 19, 'That was a genuine moment. I appreciate it.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'I kiss because it feels right, not because I must.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'Connection for its own sake is beautiful.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'No reward needed. The experience is enough.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'I don\'t need a reason. I just need to be present.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'This moment exists because we chose to create it.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'I find peace in these unscripted exchanges.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'The value is in the doing, not the outcome.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'Purpose finds us when we stop seeking it elsewhere.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'I am complete in this shared breath. Nothing more is required.', 'emote_kiss, Autotelic'),
-- FSB_ChatterType::Autistic (20)
(0, 0, 0, 30, 20, 'Your lips registered at 36.8 degrees Celsius. Nice.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'The pressure was exactly 4.2 newtons. Perfect.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'I felt that in my entire nervous system. Wow.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'The duration was 0.8 seconds. Optimal contact time.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'My dopamine receptors are showing a 340% increase.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'The texture of your lips has a friction coefficient of 0.3.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'Auditory input detected: heartbeat elevated by 22 BPM.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'That registered as 7 distinct nerve clusters firing simultaneously.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'I have catalogued this sensation as Category A: Pleasant.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'Requesting permission to initiate another data collection session.', 'emote_kiss, Autistic');
