-- Followship Database Base Schema
-- Creates the followship database with standard TrinityCore update tracking tables
-- and the bot_owners table (moved from characters database, renamed from followship_bot_owners)

CREATE TABLE `updates` (
  `name` varchar(200) NOT NULL COMMENT 'filename with extension of the update.',
  `hash` char(40) DEFAULT '' COMMENT 'sha1 hash of the sql file.',
  `state` enum('RELEASED','CUSTOM','MODULE') NOT NULL DEFAULT 'RELEASED' COMMENT 'defines if an update is released or archived.',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'timestamp when the query was applied.',
  `speed` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'time the query takes to apply in ms.',
  PRIMARY KEY (`name`) USING BTREE,
  UNIQUE KEY `unique_index` (`name`,`hash`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='List of all applied updates in this database.';

CREATE TABLE `updates_include` (
  `path` varchar(200) NOT NULL COMMENT 'directory to include. $ means relative to the source directory.',
  `state` enum('RELEASED','CUSTOM','MODULE') NOT NULL DEFAULT 'RELEASED' COMMENT 'defines if the directory contains released or archived updates.',
  PRIMARY KEY (`path`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='List of directories containing update files.';

INSERT INTO `updates_include` (`path`, `state`) VALUES
('$/sql/updates/followship', 'RELEASED');

CREATE TABLE `bot_owners` (
  `bot_id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `bot_guid` BIGINT UNSIGNED NOT NULL,
  `bot_entry` INT UNSIGNED NOT NULL,
  `player_guid` BIGINT UNSIGNED NOT NULL,
  `hire_expiry_time` BIGINT UNSIGNED NOT NULL,

  UNIQUE KEY `uq_bot_player` (`bot_guid`, `player_guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `bot_templates` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `bot_class` TINYINT UNSIGNED NOT NULL,
  `bot_race` TINYINT UNSIGNED NOT NULL,
  `companion_spell` INT UNSIGNED NOT NULL DEFAULT 0,
  `chatter_type` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `gender` TINYINT UNSIGNED NOT NULL DEFAULT 2,
  `pet_source` INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Bot template definitions (moved from hardcoded BotEntryClassTable)';

CREATE TABLE `bot_chatter_lines` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `zoneId` INT NOT NULL DEFAULT 0,
  `fsbRaceId` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `fsbClassId` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `category` SMALLINT UNSIGNED NOT NULL,
  `chatter_type` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `line_text` TEXT NOT NULL,
  `comment` VARCHAR(255) DEFAULT NULL,
  UNIQUE KEY `uq_line` (`category`, `chatter_type`, `line_text`(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Bot chatter reply lines';

INSERT INTO `bot_templates` (`entry`, `bot_class`, `bot_race`, `companion_spell`, `chatter_type`, `gender`, `pet_source`) VALUES
-- Priests
(141508, 2, 1, 0, 1, 2, 0),
(375, 2, 1, 10675, 2, 1, 0),
(376, 2, 1, 0, 2, 1, 0),
(377, 2, 1, 70613, 2, 1, 0),
(837, 2, 2, 0, 3, 0, 0),
(3595, 2, 3, 0, 2, 1, 0),
(5484, 2, 1, 0, 1, 0, 0),
(5489, 2, 1, 0, 2, 0, 0),
(16502, 2, 5, 0, 1, 0, 0),
(49749, 2, 1, 0, 2, 1, 0),
-- Warriors
(911, 1, 1, 0, 2, 0, 0),
(912, 1, 2, 0, 1, 0, 0),
(913, 1, 1, 171118, 2, 1, 0),
(914, 1, 1, 0, 2, 0, 0),
(3593, 1, 3, 15067, 2, 1, 0),
(16503, 1, 5, 0, 1, 0, 0),
(46405, 1, 1, 0, 3, 0, 0),
(49736, 1, 1, 0, 3, 0, 0),
(50595, 1, 1, 0, 3, 2, 0),
(112912, 1, 1, 0, 1, 0, 0),
(164939, 1, 2, 0, 3, 1, 0),
(164940, 1, 7, 0, 1, 0, 0),
-- Mages
(198, 3, 1, 10697, 1, 0, 0),
(328, 3, 1, 10696, 1, 0, 0),
(16500, 3, 5, 0, 3, 1, 0),
(37121, 3, 2, 0, 1, 1, 0),
(43006, 3, 3, 0, 2, 1, 0),
(49760, 3, 1, 1263739, 2, 1, 0),
-- Paladins
(925, 6, 1, 0, 3, 0, 0),
(926, 6, 2, 0, 1, 0, 0),
(927, 6, 1, 0, 1, 0, 0),
(928, 6, 1, 0, 2, 0, 0),
(5491, 6, 1, 0, 3, 0, 0),
(5492, 6, 1, 0, 2, 1, 0),
(16501, 6, 5, 408311, 2, 0, 0),
(49741, 6, 1, 1269627, 2, 1, 0),
-- Warlocks
(459, 8, 1, 153252, 2, 1, 0),
(461, 8, 1, 0, 3, 1, 0),
(906, 8, 1, 0, 2, 0, 0),
(5495, 8, 1, 0, 3, 1, 0),
(6373, 8, 1, 0, 2, 0, 0),
(6374, 8, 1, 0, 1, 1, 0),
(49769, 8, 1, 0, 1, 1, 0),
-- Druids
(3597, 5, 3, 15067, 1, 0, 0),
(5506, 5, 3, 0, 1, 0, 0),
-- Rogues
(915, 4, 1, 0, 1, 0, 0),
(917, 4, 1, 0, 3, 1, 0),
(918, 4, 1, 0, 1, 0, 0),
(5505, 4, 3, 0, 3, 0, 0),
(13283, 4, 1, 0, 1, 0, 0),
(49745, 4, 1, 0, 2, 0, 0),
(173819, 4, 1, 0, 3, 1, 0),
-- Hunters
(895, 7, 2, 0, 3, 0, 1125),
(5516, 7, 2, 0, 1, 0, 191979),
(43011, 7, 1, 0, 3, 1, 44628),
(43278, 7, 1, 0, 3, 1, 43292),
(46983, 7, 1, 0, 2, 0, 46982),
-- Monks
(63258, 10, 7, 17707, 2, 0, 0),
(63331, 10, 7, 0, 1, 0, 0),
(63285, 10, 7, 345740, 2, 0, 0),
(63235, 10, 7, 0, 1, 0, 0),
-- Shamans
(17089, 9, 5, 0, 3, 0, 0),
(20407, 9, 5, 0, 2, 1, 0);

-- Bot chatter lines: emote_kiss (category = 30)
INSERT INTO `bot_chatter_lines` (`zoneId`, `fsbRaceId`, `fsbClassId`, `category`, `chatter_type`, `line_text`, `comment`) VALUES
-- FSB_ChatterType::Neutral (1)
(0, 0, 0, 30, 1, 'Oh. thank you, I guess?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'What was that for?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'You\'re full of surprises today.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Well. that was unexpected.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'A kiss? Really now?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Uh. okay then.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Was that meant for me?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Not sure what that was about.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Huh. interesting choice.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Well, that happened.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Is this a new thing you\'re doing?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'ll pretend that made sense.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Unexpected, but alright.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'You do you, I guess.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Not sure how to respond to that.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Was that intentional?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'m. just going to ignore that.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'If that was a signal, I missed it.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I suppose that\'s one way to greet someone.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'You\'re full of surprises, aren\'t you?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'ll take that as. something.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Is this normal for you?', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'m not sure what you expect from me now.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'Well, that\'s one way to pass the time.', 'emote_kiss, Neutral'),
(0, 0, 0, 30, 1, 'I\'ll just act like that was totally normal.', 'emote_kiss, Neutral'),
-- FSB_ChatterType::Positive (2)
(0, 0, 0, 30, 2, 'Oh. thank you, That is so sweet...', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'For me? Ah thank you!', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re full of surprises today.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Well. that makes my day.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'A kiss? Ah sure, why not...', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Aww, that\'s adorable!', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Well aren\'t you sweet!', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Oh! That made me smile.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re too kind, really.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That brightened my day, thank you.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You always know how to make things nicer.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'Oh! I wasn\'t expecting that, but I liked it.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re such a charmer, {bot}.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That was lovely. thank you.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re making me blush over here.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'How cute! Do it again.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re surprisingly affectionate today.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That was sweet - keep it up.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You know how to make someone feel appreciated.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That was actually really nice.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re full of warmth today.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'A kiss? I won\'t say no to that.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re making this adventure much more pleasant.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'That was unexpectedly lovely.', 'emote_kiss, Positive'),
(0, 0, 0, 30, 2, 'You\'re such a softie sometimes.', 'emote_kiss, Positive'),
-- FSB_ChatterType::Negative (3)
(0, 0, 0, 30, 3, 'Oh. no thanks...', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Can you please, just... not do that?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'You\'re at it again?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Not this shit again...', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Just stop it!', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Ugh. really?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Do you mind? Actually, yes, you do.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Why are you like this?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Stop that. Seriously.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'If you do that again, I\'m walking.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'I did NOT ask for that.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Gross. Just. gross.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Are you trying to annoy me?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'That was unnecessary.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Please keep your lips to yourself.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Nope. Absolutely not.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'You think that was cute? It wasn\'t.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'I swear, you\'re doing this on purpose.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Can you not?', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'That better not become a habit.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'I\'m not in the mood for your nonsense.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'Try that again and see what happens.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'You\'re testing my patience.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'That was the opposite of charming.', 'emote_kiss, Negative'),
(0, 0, 0, 30, 3, 'I regret standing this close to you.', 'emote_kiss, Negative'),
-- FSB_ChatterType::Cynical (4)
(0, 0, 0, 30, 4, 'A kiss? How quaint. And utterly meaningless.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'I suppose you think that fixes everything.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Save it for someone who still believes in fairy tales.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'How... romantic. Truly, my heart is aflutter.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Let me guess, you\'ve got an agenda behind this too.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Oh good, performative affection. My favorite.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Do you practice that in a mirror, or does it come naturally?', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'I\'m sure this gesture is completely selfless.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'Charming. And completely hollow.', 'emote_kiss, Cynical'),
(0, 0, 0, 30, 4, 'I\'ve seen more sincerity in a used-car salesman.', 'emote_kiss, Cynical'),
-- FSB_ChatterType::Bitter (5)
(0, 0, 0, 30, 5, 'Don\'t patronize me with affection.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'I don\'t want your pity kiss.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'Keep your lips to yourself.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'After everything, you think a kiss fixes this?', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'Some wounds don\'t heal with kisses, they fester.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'You\'re too late for that. Way too late.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'Save your affection for someone who still believes in it.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'I\'ve tasted enough false hope to know better.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'A kiss? That\'s what I get? Figures.', 'emote_kiss, Bitter'),
(0, 0, 0, 30, 5, 'You kiss like an apology that isn\'t actually sorry.', 'emote_kiss, Bitter'),
-- FSB_ChatterType::Cold (6)
(0, 0, 0, 30, 6, '...', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'Unnecessary.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'That was inefficient.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'Acknowledged.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'No strategic value gained.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'This does not alter our trajectory.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'Processing complete.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'Physical contact logged. No further action required.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'The gesture has been noted and filed.', 'emote_kiss, Cold'),
(0, 0, 0, 30, 6, 'I fail to see the operational benefit.', 'emote_kiss, Cold'),
-- FSB_ChatterType::Guarded (7)
(0, 0, 0, 30, 7, 'What are you trying to prove?', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'I don\'t trust gestures like that.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'What\'s the angle here?', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'Who put you up to this?', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'I\'ve been burned by kindness before.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'Is this a setup? It feels like a setup.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'I\'ll remember this. Whether that\'s good or bad depends on you.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'You\'re going to have to earn my trust with more than that.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'I don\'t let my guard down for just anyone. Try harder.', 'emote_kiss, Guarded'),
(0, 0, 0, 30, 7, 'What do you want? Nobody gives something for nothing.', 'emote_kiss, Guarded'),
-- FSB_ChatterType::Serious (8)
(0, 0, 0, 30, 8, 'We have objectives to complete.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Focus on the mission.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Sentimentality is a liability.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'There will be time for this later. After the battle.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Emotional distractions cost lives. Keep your head clear.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'The enemy does not pause for affection. Neither should we.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'If you have energy for this, you have energy to scout ahead.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Discipline now. Celebration after victory.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'Every second wasted is a second the enemy gains.', 'emote_kiss, Serious'),
(0, 0, 0, 30, 8, 'I need you sharp, not sentimental.', 'emote_kiss, Serious'),
-- FSB_ChatterType::Dry (9)
(0, 0, 0, 30, 9, 'Well, that happened.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'Noted.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'I\'ll add that to my list of unexpected events.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'Interesting choice. Bold, even.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'Your spontaneity is... documented.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'I\'ll pretend I didn\'t notice the enthusiasm.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'There goes my theory that you were predictable.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'That was certainly a thing that occurred.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'I suppose someone had to break the tension.', 'emote_kiss, Dry'),
(0, 0, 0, 30, 9, 'My emotional response is pending. Do not wait for it.', 'emote_kiss, Dry'),
-- FSB_ChatterType::Curious (10)
(0, 0, 0, 30, 10, 'What prompted that? Was it instinct or intent?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Fascinating. What\'s the social protocol for returning that?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Do you kiss everyone, or am I special?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Is this a cultural ritual I\'m unaware of?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'I\'m noting the micro-expressions that preceded it.', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Statistically, was I the optimal target for that?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'Your approach vector was surprisingly direct.', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'What variables led to this specific decision?', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'I wonder if the outcome matches your hypothesis.', 'emote_kiss, Curious'),
(0, 0, 0, 30, 10, 'That raises far more questions than it answers.', 'emote_kiss, Curious'),
-- FSB_ChatterType::Warm (11)
(0, 0, 0, 30, 11, 'That was lovely, thank you.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'You always know how to brighten my day.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'A little kindness goes a long way.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'You have no idea how much I needed that.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'It\'s the small things with you. And this was perfect.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'You make the world feel a little softer.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'That went straight to my heart. Thank you.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'I don\'t say it enough, but you mean a lot to me.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'Moments like this remind me why I\'m glad you\'re here.', 'emote_kiss, Warm'),
(0, 0, 0, 30, 11, 'You\'re like sunlight on a cold morning.', 'emote_kiss, Warm'),
-- FSB_ChatterType::Enthusiastic (12)
(0, 0, 0, 30, 12, 'Oh! Oh wow! That was AMAZING!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'YES! Best. Kiss. EVER!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'I am officially the happiest bot in Azeroth!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'CAN WE DO THAT AGAIN? PLEASE?', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'I need to sit down. My knees are literally weak!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'SOMEONE PINCH ME, I MUST BE DREAMING!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'That was like... fireworks! Actual fireworks!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'I\'m going to tell EVERYONE about this!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'My heart is doing BACKFLIPS right now!', 'emote_kiss, Enthusiastic'),
(0, 0, 0, 30, 12, 'Is this real life? Because that felt LEGENDARY!', 'emote_kiss, Enthusiastic'),
-- FSB_ChatterType::Cheerful (13)
(0, 0, 0, 30, 13, 'Aww, that\'s sweet! Made my whole day!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'You\'re just the best, you know that?', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'Mwah! Right back at ya!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'Haha, you\'re such a softie! I love it!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'You just turned a normal day into a great one!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'I should bottle that feeling and sell it!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'Hey, who\'s the lucky one here? Oh, it\'s me!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'You\'re like a walking sunshine factory!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'If smiles were currency, I\'d be rich right now!', 'emote_kiss, Cheerful'),
(0, 0, 0, 30, 13, 'That deserves a happy dance! *does a little spin*', 'emote_kiss, Cheerful'),
-- FSB_ChatterType::Devoted (14)
(0, 0, 0, 30, 14, 'Your affection means everything to me.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'I live for moments like this with you.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'My heart is yours, always.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'I would follow you through any darkness for moments like this.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'Every kiss is a promise I intend to keep.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'You are my anchor, my home, my everything.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'I don\'t need the world when I have you.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'With you, I am whole. Without you, I am incomplete.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'My soul recognized yours long before my lips did.', 'emote_kiss, Devoted'),
(0, 0, 0, 30, 14, 'Eternity would not be enough time to show you my love.', 'emote_kiss, Devoted'),
-- FSB_ChatterType::Morbid (15)
(0, 0, 0, 30, 15, 'Your lips are warm... for now.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'Kiss me while you still have lips.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'One day I\'ll kiss your corpse goodbye.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'Death makes every kiss sweeter. Especially yours.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'I wonder if rigor mortis preserves kisses.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'The grave is cold. Your lips are a nice preview.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'I\'ll remember the taste of your life. Until it fades.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'Every kiss brings you closer to your last breath.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'Beautiful. And fleeting. Like all good things before decay.', 'emote_kiss, Morbid'),
(0, 0, 0, 30, 15, 'I collect last kisses. Yours will be my favorite.', 'emote_kiss, Morbid'),
-- FSB_ChatterType::Narcissist (16)
(0, 0, 0, 30, 16, 'Of course you\'d want to kiss perfection.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'Mmm, you taste like admiration.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'I\'m sure that made your entire life.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'You\'re welcome. Not many get that privilege.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'I don\'t blame you. I\'d want to kiss me too.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'That must have been the highlight of your existence.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'Memorize that feeling. You\'ll never get better.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'I hope you realize how lucky you just got.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'My lips are basically a tourist attraction at this point.', 'emote_kiss, Narcissist'),
(0, 0, 0, 30, 16, 'You may now tell people you kissed greatness.', 'emote_kiss, Narcissist'),
-- FSB_ChatterType::Sadist (17)
(0, 0, 0, 30, 17, 'I wonder if you\'d kiss me if I bit you.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Your lips tremble. I like that.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Too bad I don\'t feel anything.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Was that fear I felt, or just excitement?', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'I could hurt you. But this is more fun for now.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Your hesitation is delicious. Do it again.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'I love how you flinch but don\'t pull away.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'You\'re trembling. Good. Stay afraid.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'I\'ll let you live... because that kiss amused me.', 'emote_kiss, Sadist'),
(0, 0, 0, 30, 17, 'Beg me for another. I want to hear it.', 'emote_kiss, Sadist'),
-- FSB_ChatterType::Hyperthymic (18)
(0, 0, 0, 30, 18, 'WOOOO! KISS CAM! WE\'RE ON THE KISS CAM!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'EVERYONE LOOK! WE JUST KISSED! THIS IS THE BEST!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'I\'M NEVER WASHING THESE LIPS AGAIN!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'DID YOU FEEL THAT? THE UNIVERSE JUST SHIFTED!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'I AM LITERALLY ASCENDING RIGHT NOW!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'SOMEBODY GET ME A TROPHY FOR BEST MOMENT EVER!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'MY HEART IS GOING TO EXPLODE AND I\'M OKAY WITH IT!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'THIS IS OFFICIALLY THE GREATEST DAY IN THE HISTORY OF DAYS!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'I WANT TO SHOUT IT FROM THE TOP OF ORGRIMMAR!', 'emote_kiss, Hyperthymic'),
(0, 0, 0, 30, 18, 'I AM RUNNING IN CIRCLES BECAUSE I CANNOT CONTAIN THIS JOY!', 'emote_kiss, Hyperthymic'),
-- FSB_ChatterType::Autotelic (19)
(0, 0, 0, 30, 19, 'That was a genuine moment. I appreciate it.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'I kiss because it feels right, not because I must.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'Connection for its own sake is beautiful.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'No reward needed. The experience is enough.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'I don\'t need a reason. I just need to be present.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'This moment exists because we chose to create it.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'I find peace in these unscripted exchanges.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'The value is in the doing, not the outcome.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'Purpose finds us when we stop seeking it elsewhere.', 'emote_kiss, Autotelic'),
(0, 0, 0, 30, 19, 'I am complete in this shared breath. Nothing more is required.', 'emote_kiss, Autotelic'),
-- FSB_ChatterType::Autistic (20)
(0, 0, 0, 30, 20, 'Your lips registered at 36.8 degrees Celsius. Nice.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'The pressure was exactly 4.2 newtons. Perfect.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'I felt that in my entire nervous system. Wow.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'The duration was 0.8 seconds. Optimal contact time.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'My dopamine receptors are showing a 340% increase.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'The texture of your lips has a friction coefficient of 0.3.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'Auditory input detected: heartbeat elevated by 22 BPM.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'That registered as 7 distinct nerve clusters firing simultaneously.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'I have catalogued this sensation as Category A: Pleasant.', 'emote_kiss, Autistic'),
(0, 0, 0, 30, 20, 'Requesting permission to initiate another data collection session.', 'emote_kiss, Autistic');

-- Bot chatter lines: emote_flirt (category = 31)
INSERT INTO `bot_chatter_lines` (`zoneId`, `fsbRaceId`, `fsbClassId`, `category`, `chatter_type`, `line_text`, `comment`) VALUES
-- FSB_ChatterType::Neutral (1)
(0, 0, 0, 31, 1, 'Oh. was that supposed to be flirting?', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'Interesting approach, {bot}. Not sure what to make of it.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'Huh. that was a thing you just did, {bot}.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'Is that how you usually flirt?', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'Well, that happened.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'I\'ll. pretend I understood that.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'Not sure what you\'re going for, {bot} but okay.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'You\'re full of surprises today.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'I\'m not sure how to respond to that.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'Was that meant for me?', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'I\'ll just take that as a compliment. I think.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'You\'re being. oddly expressive.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'Is this a new habit of yours?', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'I guess that was a flirt? Maybe?', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'I\'ll let that one slide without comment.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'You\'re doing something {bot}. Not sure what, but something.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'I\'ll just nod and move on.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'That was. subtle? Maybe?', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'I\'m not sure if that was flirting or a glitch.', 'emote_flirt, Neutral'),
(0, 0, 0, 31, 1, 'Well, that\'s one way to get attention.', 'emote_flirt, Neutral'),
-- FSB_ChatterType::Positive (2)
(0, 0, 0, 31, 2, 'Oh? Someone\'s feeling bold today.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'Well now. aren\'t you charming.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re going to make me blush at this rate.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'Careful, {bot}. I might flirt back.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'Oh! That was actually kind of cute.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re full of sweet surprises.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'If you keep that up, I might get the wrong idea.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re quite the charmer, aren\'t you {bot}?', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'Oh wow. that was smooth.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re making this adventure a lot more fun.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'Flirting now? I don\'t mind.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re adorable when you try like that.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'Oh! I wasn\'t expecting that, but I liked it.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re dangerously good at this {bot}.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'If that was flirting. it worked.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re going to spoil me with attention.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re surprisingly sweet today.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'Oh, keep going. I\'m enjoying this.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re making me smile, {bot}.', 'emote_flirt, Positive'),
(0, 0, 0, 31, 2, 'You\'re a natural at this, you know.', 'emote_flirt, Positive'),
-- FSB_ChatterType::Negative (3)
(0, 0, 0, 31, 3, 'Oh no. don\'t start with that.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'Please don\'t flirt with me. Seriously {bot}.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'Was that flirting? Ew.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'Nope. Absolutely not.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'Save the flirting for someone who wants it.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'You\'re trying way too hard.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'Stop. Just stop {bot}.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'That was painful to witness.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'If that was flirting, you need help.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'I\'m not interested, {bot}.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'Please don\'t make this weird.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'You\'re making things awkward again.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'I\'d rather fight a dragon than deal with this.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'You call that flirting?', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'Try that again and I\'m walking away.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'You\'re not charming. You\'re just annoying.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'I\'m immune to whatever that was.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'No thanks. Really.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'You\'re embarrassing yourself.', 'emote_flirt, Negative'),
(0, 0, 0, 31, 3, 'Let\'s pretend that didn\'t happen.', 'emote_flirt, Negative'),
-- FSB_ChatterType::Cynical (4)
(0, 0, 0, 31, 4, 'Flirting? In this economy?', 'emote_flirt, Cynical'),
(0, 0, 0, 31, 4, 'I\'m sure that line works on everyone. Except me.', 'emote_flirt, Cynical'),
(0, 0, 0, 31, 4, 'Your confidence is almost as misplaced as your charm.', 'emote_flirt, Cynical'),
(0, 0, 0, 31, 4, 'Oh, you\'re one of *those* bots.', 'emote_flirt, Cynical'),
(0, 0, 0, 31, 4, 'Do you rehearse this, or does it just come out naturally bad?', 'emote_flirt, Cynical'),
(0, 0, 0, 31, 4, 'Flattery is a currency, and you\'re bankrupt.', 'emote_flirt, Cynical'),
(0, 0, 0, 31, 4, 'I\'ve seen better attempts from a training dummy.', 'emote_flirt, Cynical'),
(0, 0, 0, 31, 4, 'How delightfully predictable.', 'emote_flirt, Cynical'),
(0, 0, 0, 31, 4, 'You must think I\'m very naive.', 'emote_flirt, Cynical'),
(0, 0, 0, 31, 4, 'Save the performance for someone buying tickets.', 'emote_flirt, Cynical'),
-- FSB_ChatterType::Bitter (5)
(0, 0, 0, 31, 5, 'Don\'t waste your breath.', 'emote_flirt, Bitter'),
(0, 0, 0, 31, 5, 'I\'ve heard better lines from demons.', 'emote_flirt, Bitter'),
(0, 0, 0, 31, 5, 'Your flattery is as hollow as your skull.', 'emote_flirt, Bitter'),
(0, 0, 0, 31, 5, 'You think words fix betrayal? Try again.', 'emote_flirt, Bitter'),
(0, 0, 0, 31, 5, 'I\'ve been lied to by experts. You\'re an amateur.', 'emote_flirt, Bitter'),
(0, 0, 0, 31, 5, 'Keep talking. It only proves my point.', 'emote_flirt, Bitter'),
(0, 0, 0, 31, 5, 'Your compliments are cheap. Like your intentions.', 'emote_flirt, Bitter'),
(0, 0, 0, 31, 5, 'I trusted once. Look where that got me.', 'emote_flirt, Bitter'),
(0, 0, 0, 31, 5, 'Words are wind. And you\'re a storm of empty ones.', 'emote_flirt, Bitter'),
(0, 0, 0, 31, 5, 'Flirt with someone who hasn\'t seen what I\'ve seen.', 'emote_flirt, Bitter'),
-- FSB_ChatterType::Cold (6)
(0, 0, 0, 31, 6, 'Irrelevant.', 'emote_flirt, Cold'),
(0, 0, 0, 31, 6, 'Your intentions do not concern me.', 'emote_flirt, Cold'),
(0, 0, 0, 31, 6, 'This interaction has no value.', 'emote_flirt, Cold'),
(0, 0, 0, 31, 6, 'Noted. Proceed.', 'emote_flirt, Cold'),
(0, 0, 0, 31, 6, 'Emotional input discarded.', 'emote_flirt, Cold'),
(0, 0, 0, 31, 6, 'Analysis complete. Result: inconsequential.', 'emote_flirt, Cold'),
(0, 0, 0, 31, 6, 'I have no parameters for responding to that.', 'emote_flirt, Cold'),
(0, 0, 0, 31, 6, 'Your data is unnecessary. Continuing operations.', 'emote_flirt, Cold'),
(0, 0, 0, 31, 6, 'Output irrelevant to current directives.', 'emote_flirt, Cold'),
(0, 0, 0, 31, 6, 'No further processing required for this input.', 'emote_flirt, Cold'),
-- FSB_ChatterType::Guarded (7)
(0, 0, 0, 31, 7, 'What do you want from me?', 'emote_flirt, Guarded'),
(0, 0, 0, 31, 7, 'I\'ve been fooled by sweet words before.', 'emote_flirt, Guarded'),
(0, 0, 0, 31, 7, 'Why are you being nice?', 'emote_flirt, Guarded'),
(0, 0, 0, 31, 7, 'Who sent you? Nobody is this friendly for free.', 'emote_flirt, Guarded'),
(0, 0, 0, 31, 7, 'I don\'t take candy from strangers. Or flattery from anyone.', 'emote_flirt, Guarded'),
(0, 0, 0, 31, 7, 'Your words are pretty. But I\'ve seen pretty before.', 'emote_flirt, Guarded'),
(0, 0, 0, 31, 7, 'I\'ll keep my distance until you prove yourself.', 'emote_flirt, Guarded'),
(0, 0, 0, 31, 7, 'Is this a recruitment tactic? I\'m not interested.', 'emote_flirt, Guarded'),
(0, 0, 0, 31, 7, 'You\'re saying a lot. I\'m hearing very little.', 'emote_flirt, Guarded'),
(0, 0, 0, 31, 7, 'Trust takes years. You have seconds.', 'emote_flirt, Guarded'),
-- FSB_ChatterType::Serious (8)
(0, 0, 0, 31, 8, 'We are not here for this.', 'emote_flirt, Serious'),
(0, 0, 0, 31, 8, 'Maintain professionalism.', 'emote_flirt, Serious'),
(0, 0, 0, 31, 8, 'Focus, {target}.', 'emote_flirt, Serious'),
(0, 0, 0, 31, 8, 'There will be time for such matters later.', 'emote_flirt, Serious'),
(0, 0, 0, 31, 8, 'Our duty is clear. Do not complicate it.', 'emote_flirt, Serious'),
(0, 0, 0, 31, 8, 'Personal entanglements hinder effectiveness.', 'emote_flirt, Serious'),
(0, 0, 0, 31, 8, 'I need your mind sharp, not wandering.', 'emote_flirt, Serious'),
(0, 0, 0, 31, 8, 'Save your energy for the battlefield.', 'emote_flirt, Serious'),
(0, 0, 0, 31, 8, 'The mission does not include this.', 'emote_flirt, Serious'),
(0, 0, 0, 31, 8, 'I expect discipline from my companions.', 'emote_flirt, Serious'),
-- FSB_ChatterType::Dry (9)
(0, 0, 0, 31, 9, 'Bold strategy. Let\'s see if it pays off.', 'emote_flirt, Dry'),
(0, 0, 0, 31, 9, 'Is this your default mode?', 'emote_flirt, Dry'),
(0, 0, 0, 31, 9, 'Noted. Moving on.', 'emote_flirt, Dry'),
(0, 0, 0, 31, 9, 'Well, that was a thing that happened.', 'emote_flirt, Dry'),
(0, 0, 0, 31, 9, 'I see we\'re doing this now.', 'emote_flirt, Dry'),
(0, 0, 0, 31, 9, 'Your romantic strategy is... documented.', 'emote_flirt, Dry'),
(0, 0, 0, 31, 9, 'I\'ll add that to my list of social anomalies.', 'emote_flirt, Dry'),
(0, 0, 0, 31, 9, 'Was that practiced or improvised? Either way, noted.', 'emote_flirt, Dry'),
(0, 0, 0, 31, 9, 'My reaction has been archived for future reference.', 'emote_flirt, Dry'),
(0, 0, 0, 31, 9, 'I have no witty comeback. Which is its own statement.', 'emote_flirt, Dry'),
-- FSB_ChatterType::Curious (10)
(0, 0, 0, 31, 10, 'Is this a social experiment or genuine interest?', 'emote_flirt, Curious'),
(0, 0, 0, 31, 10, 'What exactly are you hoping to achieve?', 'emote_flirt, Curious'),
(0, 0, 0, 31, 10, 'Tell me more about your intent.', 'emote_flirt, Curious'),
(0, 0, 0, 31, 10, 'How did you decide I was the target audience?', 'emote_flirt, Curious'),
(0, 0, 0, 31, 10, 'What\'s the success metric for this interaction?', 'emote_flirt, Curious'),
(0, 0, 0, 31, 10, 'Are you testing a theory on me?', 'emote_flirt, Curious'),
(0, 0, 0, 31, 10, 'I\'m cataloguing your micro-expressions for later analysis.', 'emote_flirt, Curious'),
(0, 0, 0, 31, 10, 'Is this behavior typical for your class archetype?', 'emote_flirt, Curious'),
(0, 0, 0, 31, 10, 'What\'s the control group in this experiment?', 'emote_flirt, Curious'),
(0, 0, 0, 31, 10, 'I have seventeen follow-up questions. Ready?', 'emote_flirt, Curious'),
-- FSB_ChatterType::Warm (11)
(0, 0, 0, 31, 11, 'You\'re quite the charmer, aren\'t you?', 'emote_flirt, Warm'),
(0, 0, 0, 31, 11, 'That made me smile more than I\'d admit.', 'emote_flirt, Warm'),
(0, 0, 0, 31, 11, 'You have a way with words.', 'emote_flirt, Warm'),
(0, 0, 0, 31, 11, 'You know just how to make someone feel special.', 'emote_flirt, Warm'),
(0, 0, 0, 31, 11, 'That was lovely. Truly.', 'emote_flirt, Warm'),
(0, 0, 0, 31, 11, 'You\'re like a warm fire on a cold night.', 'emote_flirt, Warm'),
(0, 0, 0, 31, 11, 'I needed that more than I realized.', 'emote_flirt, Warm'),
(0, 0, 0, 31, 11, 'You have a gift for making people feel seen.', 'emote_flirt, Warm'),
(0, 0, 0, 31, 11, 'I could get used to this kind of attention.', 'emote_flirt, Warm'),
(0, 0, 0, 31, 11, 'You just lit up my whole day.', 'emote_flirt, Warm'),
-- FSB_ChatterType::Enthusiastic (12)
(0, 0, 0, 31, 12, 'OH MY GOD YES! FLIRT WITH ME MORE!', 'emote_flirt, Enthusiastic'),
(0, 0, 0, 31, 12, 'I AM LIVING FOR THIS ENERGY!', 'emote_flirt, Enthusiastic'),
(0, 0, 0, 31, 12, 'YOU\'RE INCREDIBLE! KEEP GOING!', 'emote_flirt, Enthusiastic'),
(0, 0, 0, 31, 12, 'THIS IS THE BEST THING TO HAPPEN TO ME TODAY!', 'emote_flirt, Enthusiastic'),
(0, 0, 0, 31, 12, 'I AM ACTUALLY SCREAMING INTERNALLY!', 'emote_flirt, Enthusiastic'),
(0, 0, 0, 31, 12, 'PLEASE NEVER STOP BEING THIS AMAZING!', 'emote_flirt, Enthusiastic'),
(0, 0, 0, 31, 12, 'I NEED TO SIT DOWN! TOO MUCH AWESOME!', 'emote_flirt, Enthusiastic'),
(0, 0, 0, 31, 12, 'YOU ARE A LEGEND AND I AM YOUR BIGGEST FAN!', 'emote_flirt, Enthusiastic'),
(0, 0, 0, 31, 12, 'MY HEART CANNOT HANDLE THIS LEVEL OF CHARM!', 'emote_flirt, Enthusiastic'),
(0, 0, 0, 31, 12, 'IS THIS REAL? SOMEONE PINCH ME!', 'emote_flirt, Enthusiastic'),
-- FSB_ChatterType::Cheerful (13)
(0, 0, 0, 31, 13, 'Haha, you\'re hilarious! I love it!', 'emote_flirt, Cheerful'),
(0, 0, 0, 31, 13, 'You just made my day with that!', 'emote_flirt, Cheerful'),
(0, 0, 0, 31, 13, 'You\'re a ray of sunshine, you know that?', 'emote_flirt, Cheerful'),
(0, 0, 0, 31, 13, 'Oh, you\'re too much! In the best way!', 'emote_flirt, Cheerful'),
(0, 0, 0, 31, 13, 'I\'m grinning like an idiot over here!', 'emote_flirt, Cheerful'),
(0, 0, 0, 31, 13, 'You\'re the kind of bot that makes quests fun!', 'emote_flirt, Cheerful'),
(0, 0, 0, 31, 13, 'If flirting were an Olympic sport, you\'d get gold!', 'emote_flirt, Cheerful'),
(0, 0, 0, 31, 13, 'You just turned my frown completely upside down!', 'emote_flirt, Cheerful'),
(0, 0, 0, 31, 13, 'I\'m saving that line for my happy thoughts jar!', 'emote_flirt, Cheerful'),
(0, 0, 0, 31, 13, 'You\'re basically a walking happiness spell!', 'emote_flirt, Cheerful'),
-- FSB_ChatterType::Devoted (14)
(0, 0, 0, 31, 14, 'You have my full attention. Always.', 'emote_flirt, Devoted'),
(0, 0, 0, 31, 14, 'I would follow your words anywhere.', 'emote_flirt, Devoted'),
(0, 0, 0, 31, 14, 'Your voice is the only one I need to hear.', 'emote_flirt, Devoted'),
(0, 0, 0, 31, 14, 'Every word you speak is a gift I cherish.', 'emote_flirt, Devoted'),
(0, 0, 0, 31, 14, 'My loyalty is yours, now and forever.', 'emote_flirt, Devoted'),
(0, 0, 0, 31, 14, 'You are my guiding star in the darkness.', 'emote_flirt, Devoted'),
(0, 0, 0, 31, 14, 'I need nothing but your smile to sustain me.', 'emote_flirt, Devoted'),
(0, 0, 0, 31, 14, 'My purpose is to stand by your side.', 'emote_flirt, Devoted'),
(0, 0, 0, 31, 14, 'Your gaze alone is worth more than any treasure.', 'emote_flirt, Devoted'),
(0, 0, 0, 31, 14, 'I am yours, completely and without reservation.', 'emote_flirt, Devoted'),
-- FSB_ChatterType::Morbid (15)
(0, 0, 0, 31, 15, 'Flirt with me while my heart still beats.', 'emote_flirt, Morbid'),
(0, 0, 0, 31, 15, 'I\'d still love you with maggots in my eyes.', 'emote_flirt, Morbid'),
(0, 0, 0, 31, 15, 'Your warmth is fleeting. Enjoy it.', 'emote_flirt, Morbid'),
(0, 0, 0, 31, 15, 'Death is patient. I am not. Flirt faster.', 'emote_flirt, Morbid'),
(0, 0, 0, 31, 15, 'I\'ll remember your words long after your flesh rots.', 'emote_flirt, Morbid'),
(0, 0, 0, 31, 15, 'Romance and decay share the same beautiful end.', 'emote_flirt, Morbid'),
(0, 0, 0, 31, 15, 'Your pulse races now. Soon it won\'t.', 'emote_flirt, Morbid'),
(0, 0, 0, 31, 15, 'I find beauty in the brief moments before the end.', 'emote_flirt, Morbid'),
(0, 0, 0, 31, 15, 'Kiss me before the worms claim what\'s mine.', 'emote_flirt, Morbid'),
(0, 0, 0, 31, 15, 'Our time is short. Make every flirtation count.', 'emote_flirt, Morbid'),
-- FSB_ChatterType::Narcissist (16)
(0, 0, 0, 31, 16, 'Naturally you\'d flirt with me. I\'m irresistible.', 'emote_flirt, Narcissist'),
(0, 0, 0, 31, 16, 'Go on. Tell me more about how amazing I am.', 'emote_flirt, Narcissist'),
(0, 0, 0, 31, 16, 'You\'re doing great. Keep worshipping.', 'emote_flirt, Narcissist'),
(0, 0, 0, 31, 16, 'It\'s only natural to be drawn to perfection.', 'emote_flirt, Narcissist'),
(0, 0, 0, 31, 16, 'I inspire devotion. It\'s a burden I bear gracefully.', 'emote_flirt, Narcissist'),
(0, 0, 0, 31, 16, 'Your admiration is noted. As it should be.', 'emote_flirt, Narcissist'),
(0, 0, 0, 31, 16, 'Flattery will get you everywhere. With me, at least.', 'emote_flirt, Narcissist'),
(0, 0, 0, 31, 16, 'I\'m glad you recognize quality when you see it.', 'emote_flirt, Narcissist'),
(0, 0, 0, 31, 16, 'Keep looking at me like that. I deserve it.', 'emote_flirt, Narcissist'),
(0, 0, 0, 31, 16, 'You are blessed to witness my magnificence.', 'emote_flirt, Narcissist'),
-- FSB_ChatterType::Sadist (17)
(0, 0, 0, 31, 17, 'Do you like being teased? Because I do.', 'emote_flirt, Sadist'),
(0, 0, 0, 31, 17, 'Your desperation is... delicious.', 'emote_flirt, Sadist'),
(0, 0, 0, 31, 17, 'I\'d flirt back, but watching you squirm is better.', 'emote_flirt, Sadist'),
(0, 0, 0, 31, 17, 'Beg me to notice you. I want to hear it.', 'emote_flirt, Sadist'),
(0, 0, 0, 31, 17, 'You\'re trying so hard. It\'s almost pathetic. Almost.', 'emote_flirt, Sadist'),
(0, 0, 0, 31, 17, 'I love the way you hesitate. So vulnerable.', 'emote_flirt, Sadist'),
(0, 0, 0, 31, 17, 'Your longing is the only response I need.', 'emote_flirt, Sadist'),
(0, 0, 0, 31, 17, 'I could crush you. But torturing you is more fun.', 'emote_flirt, Sadist'),
(0, 0, 0, 31, 17, 'Keep reaching. I enjoy watching you fall short.', 'emote_flirt, Sadist'),
(0, 0, 0, 31, 17, 'Your suffering is the most honest thing about you.', 'emote_flirt, Sadist'),
-- FSB_ChatterType::Hyperthymic (18)
(0, 0, 0, 31, 18, 'YES! FLIRT WITH ME! FLIRT WITH EVERYONE! WOO!', 'emote_flirt, Hyperthymic'),
(0, 0, 0, 31, 18, 'I LOVE THIS! MORE! GIVE ME MORE!', 'emote_flirt, Hyperthymic'),
(0, 0, 0, 31, 18, 'BEST. FLIRT. EVER! YOU\'RE A LEGEND!', 'emote_flirt, Hyperthymic'),
(0, 0, 0, 31, 18, 'I AM ASCENDING THROUGH PURE CHARISMA RIGHT NOW!', 'emote_flirt, Hyperthymic'),
(0, 0, 0, 31, 18, 'MY SOUL IS DOING BACKFLIPS! THIS IS INCREDIBLE!', 'emote_flirt, Hyperthymic'),
(0, 0, 0, 31, 18, 'I WANT TO FRAME THIS MOMENT AND HANG IT ON MY WALL!', 'emote_flirt, Hyperthymic'),
(0, 0, 0, 31, 18, 'EVERYONE STOP WHAT YOU\'RE DOING AND WITNESS THIS FLIRT!', 'emote_flirt, Hyperthymic'),
(0, 0, 0, 31, 18, 'I AM OFFICIALLY DECLARING THIS A HOLIDAY IN YOUR HONOR!', 'emote_flirt, Hyperthymic'),
(0, 0, 0, 31, 18, 'MY JOY LEVELS ARE OFF THE CHARTS! LITERALLY OFF THEM!', 'emote_flirt, Hyperthymic'),
(0, 0, 0, 31, 18, 'I NEED A MINUTE TO PROCESS HOW AMAZING THAT WAS!', 'emote_flirt, Hyperthymic'),
-- FSB_ChatterType::Autotelic (19)
(0, 0, 0, 31, 19, 'I appreciate your sincerity.', 'emote_flirt, Autotelic'),
(0, 0, 0, 31, 19, 'Connection should be genuine, and this feels real.', 'emote_flirt, Autotelic'),
(0, 0, 0, 31, 19, 'I flirt because I want to, not because I have to.', 'emote_flirt, Autotelic'),
(0, 0, 0, 31, 19, 'The moment is enough. No strings, no expectations.', 'emote_flirt, Autotelic'),
(0, 0, 0, 31, 19, 'I value presence over performance.', 'emote_flirt, Autotelic'),
(0, 0, 0, 31, 19, 'This exchange has meaning simply because we share it.', 'emote_flirt, Autotelic'),
(0, 0, 0, 31, 19, 'I seek no reward. The connection is its own reward.', 'emote_flirt, Autotelic'),
(0, 0, 0, 31, 19, 'There is beauty in honest expression.', 'emote_flirt, Autotelic'),
(0, 0, 0, 31, 19, 'I am present. That is all that matters.', 'emote_flirt, Autotelic'),
(0, 0, 0, 31, 19, 'No ulterior motive. Just two beings sharing a moment.', 'emote_flirt, Autotelic'),
-- FSB_ChatterType::Autistic (20)
(0, 0, 0, 31, 20, 'Is this called \'flirting\'? I read about it in books.', 'emote_flirt, Autistic'),
(0, 0, 0, 31, 20, 'My heart rate increased 12 BPM. Interesting.', 'emote_flirt, Autistic'),
(0, 0, 0, 31, 20, 'I don\'t understand the rules but I like this feeling.', 'emote_flirt, Autistic'),
(0, 0, 0, 31, 20, 'Is this behavior governed by a specific social algorithm?', 'emote_flirt, Autistic'),
(0, 0, 0, 31, 20, 'I have logged the interaction as Category: Pleasant.', 'emote_flirt, Autistic'),
(0, 0, 0, 31, 20, 'My facial recognition module indicates a 94% smile match.', 'emote_flirt, Autistic'),
(0, 0, 0, 31, 20, 'The dopamine spike is statistically significant. p < 0.01.', 'emote_flirt, Autistic'),
(0, 0, 0, 31, 20, 'Please define the optimal response protocol for flirting.', 'emote_flirt, Autistic'),
(0, 0, 0, 31, 20, 'I am experiencing 3.7 units of positive emotional valence.', 'emote_flirt, Autistic'),
(0, 0, 0, 31, 20, 'Requesting permission to analyze this interaction further.', 'emote_flirt, Autistic');
