
// Player Notifications
constexpr auto FSB_PLAYER_NOTIFICATION_PAYMENT_SUCCESS = "Payment successful!";
constexpr auto FSB_PLAYER_NOTIFICATION_PAYMENT_FAIL = "Not enough money!";





constexpr uint32 REACT_BUFFED_CHANCE_PERCENT = 10;

// Spell Related
static constexpr uint32 NPC_GCD_MS = 1500;

// MoveChase range for spell casters
constexpr float SPELL_MAX_RANGE = 30.0f;
constexpr float SPELL_MIN_RANGE = 18.0f;



enum FSB_GenericEvents
{
    FSB_EVENT_HIRE_EXPIRED = 1,
    FSB_EVENT_HIRE_LEAVE = 2,
    FSB_EVENT_HIRE_DISMISSED = 3,
    FSB_EVENT_PERIODIC_MAINTENANCE = 4,
    FSB_EVENT_RESUME_FOLLOW = 5,
    FSB_EVENT_USE_CUSTOM_REGEN = 6,
    FSB_EVENT_MOVE_STAY = 10,
    FSB_EVENT_MOVE_FOLLOW = 11,
    FSB_EVENT_INITIATE_COMBAT = 12
};

enum FSB_PriestSpellEvents
{
    FSB_EVENT_PRIEST_OOC_MANA = 20,
    FSB_EVENT_PRIEST_OOC_HEAL_SELF = 21,
    //FSB_EVENT_PRIEST_COMBAT_SPELLS = 22,
    FSB_EVENT_PRIEST_OOC_HEAL_PLAYER = 23,
    FSB_EVENT_CHECK_COMBAT = 24,
    FSB_EVENT_PRIEST_INITIAL_COMBAT_SPELLS_PLAYER = 25,
    FSB_EVENT_PRIEST_INITIAL_COMBAT_SPELLS_SELF = 26,
    FSB_EVENT_PRIEST_OOC_RECUPERATE = 27,
    FSB_EVENT_PRIEST_IC_MANA = 28
};

enum FSB_MovementStates
{
    FSB_MOVE_STATE_IDLE = 0,
    FSB_MOVE_STATE_FOLLOWING = 1,
    FSB_MOVE_STATE_STAY = 2
};

enum FSB_Actions
{
    FSB_ACTION_INITIATE_COMBAT = 1,
    FSB_ACTION_RESURRECT_PLAYER = 2,
    FSB_ACTION_INITIAL_COMBAT_SPELLS_SELF = 3,
    FSB_ACTION_INITIAL_COMBAT_SPELLS_PLAYER = 4,
    FSB_ACTION_OOC_MANA = 5,
    FSB_ACTION_OOC_RECUPERATE = 6,
    FSB_ACTION_OOC_HEAL_SELF = 7,
    FSB_ACTION_IC_MANA = 8,
    FSB_ACTION_OOC_HEAL_PLAYER = 9,
    FSB_ACTION_COMBAT_EMERGENCY = 10,
    FSB_ACTION_COMBAT_HEAL = 11,
    FSB_ACTION_COMBAT_DAMAGE = 12
};

constexpr float FOLLOW_DISTANCE_CLOSE = 3.0f;
constexpr float FOLLOW_DISTANCE_NORMAL = 5.0f;
constexpr float FOLLOW_DISTANCE_WIDE = 8.0f;

constexpr float FOLLOW_ANGLE_BEHIND = 0.0f;
constexpr float FOLLOW_ANGLE_FRONT = M_PI;
constexpr float FOLLOW_ANGLE_LEFT = M_PI / 2.0f;
constexpr float FOLLOW_ANGLE_RIGHT = -M_PI / 2.0f;
