enum Custom_Shaman_Totem_Generic_Spells
{
    SPELL_EARTHGRAB_TOTEM = 64695,
    SPELL_MANA_TIDE_TOTEM = 320763,
    SPELL_HEALING_TIDE_TOTEM = 255021,
    SPELL_FIRE_NOVA_TOTEM = 96004,
    SPELL_CAPACITATOR_TOTEM = 118905,
    SPELL_SCORCH_TOTEM = 15037,
};

enum Custom_Shaman_Totem_Generic_NPCS
{
    NPC_EARTHGRAB_TOTEM = 60561,
    NPC_MANA_TIDE_TOTEM = 10467,
    NPC_HEALING_TIDE_TOTEM = 59764,
    NPC_FIRE_NOVA_TOTEM = 15483,
    NPC_CAPACITATOR_TOTEM = 61245,
    NPC_SCORCHING_TOTEM = 9637,
};

enum Custom_Shaman_Totem_Generic_Events
{
    EVENT_PERIODIC_SPELL_CAST = 1,
    EVENT_TIMED_SPELL_CAST_NOVA,
    EVENT_TIMED_SPELL_CAST_CAPACITATOR,
};
